title: Activities
modelClass: MartiniMultimedia\Activities\Models\Activity
list: $/martinimultimedia/activities/models/activity/columns.yaml
recordUrl: 'martinimultimedia/activities/activities/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
